apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-nginx-deploy
  labels:
    app: {{ .Release.Name }}-nginx
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-nginx
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-nginx
    spec:
      containers:
        - name: {{ .Release.Name }}-nginx
          image: {{ .Values.nginx.deployment.image }}
          imagePullPolicy: {{ .Values.nginx.deployment.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.nginx.service.port }}
          volumeMounts:
          - mountPath: /etc/nginx/conf.d/default.conf
            name: nginx-volume
      volumes:
      - name: nginx-volume
        hostPath: 
          path: /home/ubuntu/examen/nginx/nginx_config.conf