apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: {{ .Release.Name }}-nginx
  type: {{ .Values.nginx.service.type }} 
  ports:
  - name: nginx
    protocol: TCP
    port: {{ .Values.nginx.service.port }}
    targetPort: {{ .Values.nginx.service.targetPort }}
    nodePort: {{ .Values.nginx.service.nodePort }}