apiVersion: v1
kind: Service
metadata:
  name: cast-service
spec:
  selector:
    app: {{ .Release.Name }}-cast-service
  type: {{ .Values.cast.service.type }} 
  ports:
  - name: cast-service
    protocol: TCP
    port: {{ .Values.cast.service.port }}
    targetPort: {{ .Values.cast.service.targetPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: cast-db
spec:
  selector:
    app: {{ .Release.Name }}-cast-db
  type: {{ .Values.cast.service_db.type }} 
  ports:
  - name: cast-db
    protocol: TCP
    port: {{ .Values.cast.service_db.port }}
    targetPort: {{ .Values.cast.service_db.targetPort }}
