apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-movie-service-deploy
  labels:
    app: {{ .Release.Name }}-movie-service
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-movie-service
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-movie-service
    spec:
      containers:
        - name: {{ .Release.Name }}-movie-service
          image: {{ .Values.movie.deployment.image }}
          imagePullPolicy: {{ .Values.movie.deployment.imagePullPolicy }}
          tag: {{ .Values.movie.deployment.tag }}
          command: ["/bin/bash", "-c"]
          args: ["sleep 15; uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"]
          ports:
            - containerPort: {{ .Values.movie.service.port }}
          env:
            - name: DATABASE_URI
              value: postgresql://movie_db_username:movie_db_password@movie-db/movie_db_dev
            - name: CAST_SERVICE_HOST_URL
              value: http://cast_service:8000/api/v1/casts/
          volumeMounts:
          - mountPath: /app
            name: app-volume
      volumes:
      - name: app-volume
        hostPath: 
          path: /home/ubuntu/examen/movie/movie-service
      
                
