apiVersion: v1
kind: Service
metadata:
  name: movie-service
  label: {{ .Release.Name }}-movie-service
spec:
  selector:
    app: {{ .Release.Name }}-movie-service
  type: {{ .Values.movie.service.type }} 
  ports:
  - name: movie-service
    protocol: TCP
    port: {{ .Values.movie.service.port }}
    targetPort: {{ .Values.movie.service.targetPort }}
---
apiVersion: v1
kind: Service
metadata:
  name: movie-db
  label: {{ .Release.Name }}-movie-db
spec:
  selector:
    app: {{ .Release.Name }}-movie-db
  type: {{ .Values.movie.service_db.type }} 
  ports:
  - name: movie-db
    protocol: TCP
    port: {{ .Values.movie.service_db.port }}
    targetPort: {{ .Values.movie.service_db.targetPort }}
